### ISSUE TITLE
Problem of Copy.com adapter (`scandir` return empty)

### ISSUE THREAD

**Issue by nao-pon** [barryvdh/elfinder-flysystem-driver#1]
I try with
```php
use Barracuda\Copy\API;
use League\Flysystem\Filesystem;
use League\Flysystem\Copy\CopyAdapter;
$copy_consumerKey ='*****';
$copy_consumerSecret ='*****';
$copy_accessToken ='*****';
$copy_tokenSecret ='*****';
$vol_options = array(
		array(
			'driver' => 'Flysystem',
			'filesystem' => new Filesystem(new CopyAdapter(new API($copy_consumerKey, $copy_consumerSecret, $copy_accessToken, $copy_tokenSecret)))
);
```

upload, mkdir, mkfile are OK but scandir return empty array so nothing is shown to cwd when reload.

**Comment by barryvdh** [comment]
Does the Copy adapter work correctly without elFinder?

**Comment by nao-pon** [comment]
I don' t check with out elFinder. May be Flysystem's problem. 
ref. https://github.com/thephpleague/flysystem/issues/405
Thanks!

**Comment by barryvdh** [comment]
I see it's fixed upstream. Does this also solve the problem with elFinder?

**Comment by nao-pon** [comment]
Yes :+1:  Thanks!
