### ISSUE TITLE
Use Cloudinary

### ISSUE THREAD

**Issue by joaonzangoII** [barryvdh/elfinder-flysystem-driver#47]
How do I use cloudinary with elfinder?

**Comment by barryvdh** [comment]
No idea what Cloudinary is, but if you have a working flysystem adapter, it should just work

**Comment by joaonzangoII** [comment]
[Cloudinary](https://cloudinary.com/) is the market leader in providing a comprehensive cloud-based image management solution. Cloudinary is being used by tens of thousands of web and mobile application developers all around the world, from small startups to large enterprises. And you are totally right @barryvdh just needed to add some few lines of code and it works now.
