### ISSUE TITLE
can I show thumbnails for filesystem of s3 ?

### ISSUE THREAD

**Issue by wzfjesun** [barryvdh/elfinder-flysystem-driver#64]
can I show thumbnails if i use the filesystem of s3 ?
i use this lib : thephpleague/flysystem-aws-s3-v3

**Comment by barryvdh** [comment]
Yeah if you use Glide

**Comment by bayucandra** [comment]
This trick works for me without Glide: `'tmbURL' => 'self'` .

**Config detail example:**
https://github.com/bayucandra/ckeditor-elfinder/blob/master/vendor/elFinder/php/connector.minimal.php

**working demo:**
https://www.biqdev.com/demo/ckeditor-elfinder/
