### ISSUE TITLE
Driver is reading files for mimetypes instead of listing them

### ISSUE THREAD

**Issue by MickaelTH** [barryvdh/elfinder-flysystem-driver#66]
Hi,

When clicking on a folder from a disk, it often finishes with 504, meaning timeout:

![2017-12-13 002424](https://user-images.githubusercontent.com/26375917/33947731-c72aacfe-e057-11e7-9095-27a797b8f8cd.png)

The screenshot below show that commands from elFinder driver is reading a 24Mb mp4 files instead of only doing listing:

![img_13122017_194631_0](https://user-images.githubusercontent.com/26375917/33948154-c8654812-e058-11e7-8b35-76cdc1f0f0fe.png)

By doing that, elFinder timeout and show 504 as it is doing that for all files in folder. Imagine if you have 100 files of 5Mb. 

The  elFinder author found that it may be related to this:

https://github.com/barryvdh/elfinder-flysystem-driver/blob/master/src/Driver.php#L303-L323

Any idea how to mitigate this issue?

Thank you

**Comment by MickaelTH** [comment]
Meanwhile waiting for official fix, this is a dirty workaround:

![2017-12-18 002434](https://user-images.githubusercontent.com/26375917/34100750-12ef9d86-e416-11e7-96f1-4a8982217330.png)

**Comment by jblotus** [comment]
Was there ever an official fix for this? I think I am running into the same thing in flysystem-sftp - as more files are added to the server it slows down exponentially.
