### ISSUE TITLE
the visibility options reflect with the the master branch but not reflact with the last tag(v0.2.1)

### ISSUE THREAD

**Issue by yatin13490** [barryvdh/elfinder-flysystem-driver#79]
@barryvdh 

The merge pull request #72 from noogen/master reflects on the master branch with the "src/Driver.php" on line number 534.

But it does not reflect on the last tag version (v0.2.1) that why however I update my composer that changes did not show, 

can you guide me on how to fix this?

Thanks in advance.

**Comment by dmarcos89** [comment]
Same here, any solution @yatin13490 ?

**Comment by barryvdh** [comment]
https://github.com/barryvdh/elfinder-flysystem-driver/releases/tag/v0.3.0

**Comment by dmarcos89** [comment]
Thanks @barryvdh !!! Keep up the good work!!
