### ISSUE TITLE
Flysystem 2.0 Support

### ISSUE THREAD

**Issue by Muswell** [barryvdh/elfinder-flysystem-driver#80]
There is currently a hard dependency on Flysystem 1.0. Are there any plans to add support for version 2?

**Comment by GrytsenkoAndrey** [comment]
I have the same question - the newest version doesn't support flysystem 2.* and it makes problem during composer require action

**Comment by barryvdh** [comment]
Sure can you make a PR?

**Comment by dnsimmons-aaa** [comment]
Same issue here. Anxiously awaiting a fix....

**Comment by sdwru** [comment]
I am in dependency hell like a lot of other people. Since I am already using phpseclib3 I also need an updated flysystem-sftp package.

**Comment by barryvdh** [comment]
V3 support, can you test/provide feedback? https://github.com/barryvdh/elfinder-flysystem-driver/pull/83
