### ISSUE TITLE
Support for intervention/image v3

### ISSUE THREAD

**Issue by promatik** [barryvdh/elfinder-flysystem-driver#93]
[`intervention/image`](https://github.com/intervention/image) v3.0.0 was released December 2023, current version is v3.3.3, can we support it?

Upgrade guide from v2 to v3; https://image.intervention.io/v3/introduction/upgrade

**Comment by barryvdh** [comment]
PR in https://github.com/barryvdh/elfinder-flysystem-driver/pull/94
Could you test this?

**Comment by barryvdh** [comment]
You can try with `0.5@dev`
